# Generated by Django 5.2.3 on 2025-06-25 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challangeocurrance',
            old_name='notes',
            new_name='description',
        ),
    ]
