# Generated by Django 5.2.3 on 2025-06-25 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_solution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocurrence',
            old_name='description',
            new_name='notes',
        ),
        migrations.AlterField(
            model_name='ocurrence',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.safechallenges'),
        ),
        migrations.AlterField(
            model_name='ocurrence',
            name='occurred_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ocurrence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
