# Generated by Django 5.2.3 on 2025-06-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_description_ocurrence_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
