# Generated by Django 5.2.3 on 2025-07-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ocurrence_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safechallenges',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
